# -*- coding: utf-8 -*-
"""isi-distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKi_rXb9c9uoYWYiwOL2TY1jeGjzu5Dy
"""

import requests

API_KEY = "5b3ce3597851110001cf624817c89a6655584ab4941215bf9bfecc62"
BASE_URL = "https://api.openrouteservice.org/v2/directions/driving-car"
START_COORDINATE = "115.18301180914683,-8.745742493194427"
END_COORDINATE = "115.15892917017509,-8.806048249507896"

def get_directions(start: str, end: str):
    params = {
        "api_key": API_KEY,
        "start": start,
        "end": end
    }
    response = requests.get(BASE_URL, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        return {"error": response.status_code, "message": response.text}

def print_directions_data(data):
    print("Hasil Jarak:")
    distance_meters = data.get("features", [{}])[0].get("properties", {}).get("summary", {}).get("distance", 0)
    print(f"{distance_meters / 1000} km")

if __name__ == "__main__":
    startCoordinate = START_COORDINATE
    endCoordinate = END_COORDINATE
    data = get_directions(startCoordinate, endCoordinate)
    print_directions_data(data)